
#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:pulse
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:arrow-down-bold
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:arrow-up-bold



#################################################################
#                                                               #
#                          Speed Test                           #
#                                                               #
################################################################# 

speedtestdotnet:
  server_id: 2604

#################################################################
#                                                               #
#                         System Health                         #
#                                                               #
################################################################# 

system_health:

####################################################
#                                                  #
#                      WoL                         #
#                                                  #
####################################################

switch:
  - platform: wake_on_lan
    mac: 00:23:24:66:e5:b1
    name: MediaPCwol

####################################################
#                                                  #
#                     PiHole                       #
#                                                  #
####################################################

pi_hole:
  - host: 192.168.100.2


#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################

#device_tracker:

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:
  - platform: ping
    host: 192.168.100.1
    name: Router
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.254
    name: AP
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.253
    name: Switch
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.250
    name: Soundwave
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.10
    name: Shockwave
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.230
    name: Vortex
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.99.2
    name: Grimlock
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.6
    name: Skywarp
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.20
    name: Silverbolt
    scan_interval: 180
    count: 2
  - platform: ping
    host: 192.168.100.2
    name: Slingshot
    scan_interval: 180
    count: 2

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

  - platform: pfsense_gateways
    host: 192.168.100.1
    name: pfSense gateway
    key: !secret pfsense
    monitored_gateway_interfaces:
      - wan

####################################################
#                                                  #
#                 Sensor - Uptime                  #
#                                                  #
####################################################

  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

####################################################
#                                                  #
#                Sensor - File Size                #
#                                                  #
####################################################

  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
      - /config/home-assistant.log

####################################################
#                                                  #
#                Sensor - Time                     #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

#################################################################
#                                                               #
#                       Template Sensors                        #
#                                                               #
################################################################# 

  - platform: template
    sensors:
      router_state:
        friendly_name: Router
        unique_id: binary_sensor.router
        value_template: >-
          {% if is_state('binary_sensor.router', 'on') %}
            100
          {% elif is_state('binary_sensor.router', 'off') %}
            0
          {% endif %}

      switch_state:
        friendly_name: Core Switch
        unique_id: binary_sensor.switch
        value_template: >-
          {% if is_state('binary_sensor.switch', 'on') %}
              100
          {% elif is_state('binary_sensor.switch', 'off') %}
            0
          {% endif %}

      ap_state:
        friendly_name: Access Point
        unique_id: binary_sensor.ap
        value_template: >-
          {% if is_state('binary_sensor.ap', 'on') %}
              100
          {% elif is_state('binary_sensor.ap', 'off') %}
            0
          {% endif %}

      soundwave_state:
        friendly_name: Soundwave
        unique_id: binary_sensor.soundwave
        value_template: >-
          {% if is_state('binary_sensor.soundwave', 'on') %}
              100
          {% elif is_state('binary_sensor.soundwave', 'off') %}
              0
          {% endif %}
                
      shockwave_state:
        friendly_name: Shockwave
        unique_id: binary_sensor.shockwave
        value_template: >-
          {% if is_state('binary_sensor.shockwave', 'on') %}
              100
          {% elif is_state('binary_sensor.shockwave', 'off') %}
              0
          {% endif %}

      vortex_state:
        friendly_name: Vortex
        unique_id: binary_sensor.vortex
        value_template: >-
          {% if is_state('binary_sensor.vortex', 'on') %}
              100
          {% elif is_state('binary_sensor.vortex', 'off') %}
              0
          {% endif %}

      grimlock_state:
        friendly_name: Grimlock
        unique_id: binary_sensor.grimlock
        value_template: >-
          {% if is_state('binary_sensor.grimlock', 'on') %}
              100
          {% elif is_state('binary_sensor.grimlock', 'off') %}
              0
          {% endif %}

      skywarp_state:
        friendly_name: Skywarp
        unique_id: binary_sensor.skywarp
        value_template: >-
          {% if is_state('binary_sensor.skywarp', 'on') %}
              100
          {% elif is_state('binary_sensor.skywarp', 'off') %}
              0
          {% endif %}

      silverbolt_state:
        friendly_name: Silverbolt
        unique_id: binary_sensor.silverbolt
        value_template: >-
          {% if is_state('binary_sensor.silverbolt', 'on') %}
              100
          {% elif is_state('binary_sensor.silverbolt', 'off') %}
              0
          {% endif %}

      slingshot_state:
        friendly_name: Slingshot
        unique_id: binary_sensor.slingshot
        value_template: >-
          {% if is_state('binary_sensor.slingshot', 'on') %}
              100
          {% elif is_state('binary_sensor.slingshot', 'off') %}
              0
          {% endif %}
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Scripts                              #
#                                                               #
#################################################################

scripts:

  attention:
    sequence:
      - service: media_player.volume_set
        entity_id: group.all_google
        data_template:
            volume_level: 0.0
      - delay:
          seconds: 1
      - service: media_player.turn_on
        data:
          entity_id: group.all_google
      - service: media_player.volume_set
        entity_id: group.all_google
        data_template:
          volume_level: 0.6
      - delay:
          seconds: 1
      - service: media_player.play_media
        data:
          entity_id: group.all_google
          media_content_id: !secret attentiontone
          media_content_type: 'audio/mp3'
      - delay:
          seconds: 5
      - service: tts.google_translate_say
        entity_id: group.all_google
        data_template:
          message: '{{ message }}'

  garage_relay:
    alias: Garage Relay
    sequence:
      - service: switch.turn_on
        entity_id: switch.renee_garage_relay_2
      - delay:
          seconds: 1
      - service: switch.turn_off
        entity_id: switch.renee_garage_relay_2

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:


- id: 'Set-theme'
  alias: Set Theme at startup
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: GreyNight

- id: 'iOS action'
  alias: iOS action
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Garage door'
  action:
    service: script.garage_relay 

- id: 'Garage door check'
  alias: Check how long garage door is open for
  trigger:
    platform: state
    entity_id: binary_sensor.renee_garage_door_2
    to: 'on'
    for:
      minutes: 3
  action:
    - service: script.attention
      data:
        message: 'Is there a reason the garage door is open?'
    - service: notify.iphones
      data:
        message: 'Is the garage door open for a reason?'
        data:
          push:
            sound: attention-tone-new.wav

- id: 'GrafanaVPN'
  alias: GrafanaVPN
  trigger:
    platform: webhook
    webhook_id: grafanaVPN
  condition:
    condition: time
    after: "08:00:00"
  action:
    - service: script.attention
      data:
        message: 'VPN connection has dropped.'


#################################################################
#                                                               #
#                         Playground                            #
#                                                               #
#################################################################


