#################################################################
#                                                               #
#                     MQTT Control Panel                        #
#                                                               #
#################################################################

alarm_control_panel:
  - platform: manual_mqtt
    code: 4123
    state_topic: home/alarm
    command_topic: home/alarm/set

#################################################################
#                                                               #
#                     Alarm Control Panel                       #
#                                                               #
#################################################################

  - platform: manual
    name: Home Alarm
    code: 4123
    trigger_time: 10




binary_sensor:
  - platform: template
    sensors:
      alarm:
        friendly_name: Alarm
        entity_id: alarm_control_panel.ha_alarm
        value_template: >-
          {% if is_state('alarm_control_panel.ha_alarm', 'armed_home') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'armed_away') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'pending') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'triggered') %}
            on
          {% else %}
            off
          {% endif %}
        icon_template: >-
          {% if is_state('alarm_control_panel.ha_alarm', 'armed_home') %}
            mdi:shield-home
          {% elif is_state('alarm_control_panel.ha_alarm', 'armed_away') %}
            mdi:shield-lock
          {% elif is_state('alarm_control_panel.ha_alarm', 'pending') %}
            mdi:security
          {% elif is_state('alarm_control_panel.ha_alarm', 'triggered') %}
            mdi:shield-alert
          {% elif is_state('alarm_control_panel.ha_alarm', 'disarmed') %}
            mdi:shield-home
          {% else %}
            mdi:alert
          {% endif %}

#################################################################
#                                                               #
#                     Camera detection                          #
#                                                               #
#################################################################

  - platform: mqtt
    name: "Garage"
    device_class: motion
    state_topic: "BlueIris/garage"
    payload_on: "on"
    off_delay: 30
  - platform: mqtt
    name: "Entrance"
    device_class: motion
    payload_on: "on"
    state_topic: "BlueIris/entrance"
    off_delay: 30
