#################################################################
#                                                               #
#                     Alarm Control Panel                       #
#                                                               #
#################################################################

alarm_control_panel:
  - platform: manual
    code: !secret code
    name: Home Alarm
    trigger_time: 300
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_away:
      arming_time: 30
      delay_time: 30
    armed_night:
      arming_time: 0
      delay_time: 0

#################################################################
#                                                               #
#                          Scripts                              #
#                                                               #
#################################################################

script:

  arm_alarm:
    sequence:
      - service: media_player.volume_set
        entity_id: group.all_google
        data_template:
            volume_level: 0.0
      - delay:
          seconds: 1
      - service: media_player.turn_on
        data:
          entity_id: group.all_google
      - service: media_player.volume_set
        entity_id: group.all_google
        data_template:
          volume_level: 0.8
      - delay:
          seconds: 1
      - service: media_player.play_media
        data:
          entity_id: group.all_google
          media_content_id: !secret armtone
          media_content_type: 'audio/mp3'
      - delay:
          seconds: 3
      - service: tts.google_translate_say
        entity_id: group.all_google
        data_template:
          message: '{{ message }}'



#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

- id: 'announce-arming-away'
  alias: Announce the alarm is being armed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home
    from: 'disarmed'
    to: 'arming'
  action:
  - service: script.arm_alarm
    data:
      message: 'Warning, house alarm is being armed. Please exit.'

- id: 'triggered_alarm'
  alias: House alarm has been triggered
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home
    to: triggered
  action:
  - service: notify.iphones
    data:
      title: 'Alarm Triggered'
      message: 'The alarm has been triggered at home'
      data:
        push:
          sound:
            name: 'ios-alarm.wav'
            critical: 1
            volume: 1.0

- id: 'cancel_alarm'
  alias: Cancel an active house alarm
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home
    from: 'triggered'
    to: 'disarmed'
  action:
  - service: notify.iphones
    data:
      message: 'Alarm has been canceled'
      title: 'Alarm Canceled'
      data:
        push:
          badge: 5
