



switch:
- platform: template
  switches:
    sleepmusic:
      value_template: "{{ is_state('input_boolean.toggle_switch', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.play_sleep_music
      turn_off:
        service: script.turn_on
        entity_id: script.stop_sleep_music