switch:
- platform: template
  switches:
    sleepmusic:
      value_template: "{{ is_state('input_boolean.toggle_switch', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.play_sleep_music
      turn_off:
        service: script.turn_on
        entity_id: script.stop_sleep_music


#################################################################
#                                                               #
#                          Scripts                              #
#                                                               #
#################################################################

script:


  play_sleep_music:
    alias: "Sleep Music"
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.main_bedroom_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.office_speaker
          volume_level: 0.4
      - service: media_player.play_media
        entity_id: media_player.main_bedroom_speaker
        data:
          media_content_id: http://192.168.50.2:8123/local/rain.mp3
          media_content_type: "audio/mp3"
      - service: media_player.play_media
        entity_id: media_player.office_speaker
        data:
          media_content_id: http://192.168.50.2:8123/local/rain.mp3
          media_content_type: "audio/mp3"

  stop_sleep_music:
    alias: "Stop Sleep Music"
    sequence:
      - service: media_player.media_stop
        entity_id: media_player.main_bedroom_speaker