esphome:
  name: dev
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "IoT"
  password: !secret wifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev Fallback Hotspot"
    password: "JIXvG0C6JYcj"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp
  
ota:
  password: !secret esp



#light:
#  - platform: fastled_clockless
#    chipset: WS2811
#    pin: D1
#    num_leds: 120
#    rgb_order: BRG
#    default_transition_length: 1s
#    name: "Bed Back Board"
#sensor:
#  - platform: pulse_counter
#    pin:
#      number: D7
#      mode: INPUT_PULLUP   
#    unit_of_measurement: 'mm'
#    internal_filter: 15us
#    name: "${friendly_name} Rainfall"
#    filters:
#      - debounce: 1s
#      - multiply: 0.367
# This looks to be the final code for rain sensor. Just need to check the .367mm

#sensor:
#  - platform: pulse_counter
#    pin:
#      number: D7
#      inverted: True
#      mode: INPUT_PULLUP    
#    unit_of_measurement: 'km/h'
#    name: 'Windspeed'
#    update_interval: 60s
#    count_mode:
#      rising_edge: DISABLE
#      falling_edge: INCREMENT
#    internal_filter: 15us
#    filters:
      #- sliding_window_moving_average:
      #    window_size: 4
      #    send_every: 1
      #- lambda: return x * 0.458 / 60 * 3.6;
#      - multiply: 0.055578
#      - multiply: 3.6 #convert m/s to hm/h
      
      #This I am happy with.. maybe some further testing? Don't think gust would be possible
#sensor:
#  - platform: adc
#    pin: A0
#    name: "Wind Direction"
#    update_interval: 20s
#    internal: true
#    accuracy_decimals: 3
#    filters:
    #  - lambda: |-
    #      return (x / 10000.0);
    #   - multiply: 3.3 ##built into Wemos
    #   - multiply: 0.0009775171   #1/1023
          

#  - platform: resistance
#    sensor: adc_adcsensor
#    configuration: DOWNSTREAM
#    resistor: 10kOhm
#    name: Resistance Sensor
#    accuracy_decimals: 1
#    filters:
#      - heartbeat: 30s
#This is as close as I could get it but was not happy with the results. too spiradic.

##BME280
i2c:
  sda: D2
  scl: D1

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 30s
#light:
#  - platform: rgb
#    name: "test Lights"
#    red: output_component1
#    green: output_component2
#    blue: output_component3

# Example output entry
#output:
#  - platform: esp8266_pwm
#    id: output_component1
#    pin: D8
#    max_power: 80%
#  - platform: esp8266_pwm
#    id: output_component2
#    pin: D7
#    max_power: 80%
#  - platform: esp8266_pwm
#    id: output_component3
#    pin: D6
#    max_power: 80%
    
##rain sesnor
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: "rain sensor"
    device_class: door
